# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_benes/axi_benes.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_benes || ORIG_REF_NAME==axi_benes} -quiet] -quiet

# IP: bd/axi_benes/ip/axi_benes_Axi_lite_v1_0_0_0/axi_benes_Axi_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_benes_Axi_lite_v1_0_0_0 || ORIG_REF_NAME==axi_benes_Axi_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/axi_benes/ip/axi_benes_xdma_0_0/axi_benes_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_benes_xdma_0_0 || ORIG_REF_NAME==axi_benes_xdma_0_0} -quiet] -quiet

# IP: bd/axi_benes/ip/axi_benes_util_ds_buf_0/axi_benes_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_benes_util_ds_buf_0 || ORIG_REF_NAME==axi_benes_util_ds_buf_0} -quiet] -quiet

# IP: bd/axi_benes/ip/axi_benes_auto_ds_0/axi_benes_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_benes_auto_ds_0 || ORIG_REF_NAME==axi_benes_auto_ds_0} -quiet] -quiet

# IP: bd/axi_benes/ip/axi_benes_auto_pc_0/axi_benes_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_benes_auto_pc_0 || ORIG_REF_NAME==axi_benes_auto_pc_0} -quiet] -quiet

# IP: bd/axi_benes/ip/axi_benes_xdma_0_axi_periph_0/axi_benes_xdma_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_benes_xdma_0_axi_periph_0 || ORIG_REF_NAME==axi_benes_xdma_0_axi_periph_0} -quiet] -quiet

# XDC: /home/hs/Desktop/benes_axi_fck_prj/benes_axi_fck_prj.gen/sources_1/bd/axi_benes/axi_benes_ooc.xdc
