# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/alveo_u280_fhe.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_0/design_1_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xdma_0_0 || ORIG_REF_NAME==design_1_xdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Axi_lite_v1_0_0_0/design_1_Axi_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Axi_lite_v1_0_0_0 || ORIG_REF_NAME==design_1_Axi_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_axi_periph_1/design_1_xdma_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xdma_0_axi_periph_1 || ORIG_REF_NAME==design_1_xdma_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_2 || ORIG_REF_NAME==design_1_clk_wiz_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_1/design_1_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_1 || ORIG_REF_NAME==design_1_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_resetn_inv_0_1/design_1_resetn_inv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_resetn_inv_0_1 || ORIG_REF_NAME==design_1_resetn_inv_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_resetn_inv_1_1/design_1_resetn_inv_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_resetn_inv_1_1 || ORIG_REF_NAME==design_1_resetn_inv_1_1} -quiet] -quiet

# XDC: /home/hs/Desktop/xdma_axi_benes/xdma_axi_benes.gen/sources_1/bd/design_1/design_1_ooc.xdc
