# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hs/Desktop/benes_axi_fck_prj/benes_axi_fck_prj.srcs/sources_1/bd/axi_benes/ip/axi_benes_auto_pc_0/axi_benes_auto_pc_0.xci
# IP: The module: 'axi_benes_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hs/Desktop/benes_axi_fck_prj/benes_axi_fck_prj.gen/sources_1/bd/axi_benes/ip/axi_benes_auto_pc_0/axi_benes_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_benes_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hs/Desktop/benes_axi_fck_prj/benes_axi_fck_prj.srcs/sources_1/bd/axi_benes/ip/axi_benes_auto_pc_0/axi_benes_auto_pc_0.xci
# IP: The module: 'axi_benes_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hs/Desktop/benes_axi_fck_prj/benes_axi_fck_prj.gen/sources_1/bd/axi_benes/ip/axi_benes_auto_pc_0/axi_benes_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_benes_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
