webtalk_init -webtalk_dir /home/hs/Desktop/FHE/fhe_benes/fhe_interconnect/step1/vivado/check32net/check32net.sim/sim_1/behav/xsim/xsim.dir/benes_32_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 14 00:38:59 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3118627" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "db75e83e-a884-4c41-ae7f-1ad90a6941de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cb74977e0f0446e2b49a2e2f8b8f9abc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i9-12900K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4879.542 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "600 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126212_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3422312387 -regid "" -xml /home/hs/Desktop/FHE/fhe_benes/fhe_interconnect/step1/vivado/check32net/check32net.sim/sim_1/behav/xsim/xsim.dir/benes_32_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/hs/Desktop/FHE/fhe_benes/fhe_interconnect/step1/vivado/check32net/check32net.sim/sim_1/behav/xsim/xsim.dir/benes_32_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/hs/Desktop/FHE/fhe_benes/fhe_interconnect/step1/vivado/check32net/check32net.sim/sim_1/behav/xsim/xsim.dir/benes_32_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
