# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_lite_benes_0_0/design_1_axi_lite_benes_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_lite_benes_0_0 || ORIG_REF_NAME==design_1_axi_lite_benes_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_1/design_1_xdma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1 || ORIG_REF_NAME==design_1_xdma_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_1/design_1_util_ds_buf_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_1 || ORIG_REF_NAME==design_1_util_ds_buf_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_axi_periph_0/design_1_xdma_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xdma_0_axi_periph_0 || ORIG_REF_NAME==design_1_xdma_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: /home/hs/Desktop/Real_prj/xdma_axi_benes_engine/xdma_axi_benes_engine.gen/sources_1/bd/design_1/design_1_ooc.xdc
