#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 13 22:00:02 KST 2023
# SW Build 3118627 on Tue Feb  9 05:13:49 MST 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim benes_32_behav -key {Behavioral:sim_1:Functional:benes_32} -tclbatch benes_32.tcl -log simulate.log"
xsim benes_32_behav -key {Behavioral:sim_1:Functional:benes_32} -tclbatch benes_32.tcl -log simulate.log

