# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/deviceid903f/deviceid903f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f || ORIG_REF_NAME==deviceid903f} -quiet] -quiet

# IP: bd/deviceid903f/ip/deviceid903f_axi_lite_benes_0_0/deviceid903f_axi_lite_benes_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f_axi_lite_benes_0_0 || ORIG_REF_NAME==deviceid903f_axi_lite_benes_0_0} -quiet] -quiet

# IP: bd/deviceid903f/ip/deviceid903f_xdma_0_0/deviceid903f_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f_xdma_0_0 || ORIG_REF_NAME==deviceid903f_xdma_0_0} -quiet] -quiet

# IP: bd/deviceid903f/ip/deviceid903f_util_ds_buf_1/deviceid903f_util_ds_buf_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f_util_ds_buf_1 || ORIG_REF_NAME==deviceid903f_util_ds_buf_1} -quiet] -quiet

# IP: bd/deviceid903f/ip/deviceid903f_auto_ds_0/deviceid903f_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f_auto_ds_0 || ORIG_REF_NAME==deviceid903f_auto_ds_0} -quiet] -quiet

# IP: bd/deviceid903f/ip/deviceid903f_auto_pc_0/deviceid903f_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f_auto_pc_0 || ORIG_REF_NAME==deviceid903f_auto_pc_0} -quiet] -quiet

# IP: bd/deviceid903f/ip/deviceid903f_xdma_0_axi_periph_1/deviceid903f_xdma_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f_xdma_0_axi_periph_1 || ORIG_REF_NAME==deviceid903f_xdma_0_axi_periph_1} -quiet] -quiet

# IP: bd/deviceid903f/ip/deviceid903f_ila_0_0/deviceid903f_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==deviceid903f_ila_0_0 || ORIG_REF_NAME==deviceid903f_ila_0_0} -quiet] -quiet

# XDC: /home/hs/20231122/20231122.gen/sources_1/bd/deviceid903f/deviceid903f_ooc.xdc
