# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/XDMA_AXI_BENES/XDMA_AXI_BENES.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES || ORIG_REF_NAME==XDMA_AXI_BENES} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_axi_lite_benes_0_0/XDMA_AXI_BENES_axi_lite_benes_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_axi_lite_benes_0_0 || ORIG_REF_NAME==XDMA_AXI_BENES_axi_lite_benes_0_0} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_xdma_0_1/XDMA_AXI_BENES_xdma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_xdma_0_1 || ORIG_REF_NAME==XDMA_AXI_BENES_xdma_0_1} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_util_ds_buf_0/XDMA_AXI_BENES_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_util_ds_buf_0 || ORIG_REF_NAME==XDMA_AXI_BENES_util_ds_buf_0} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_xdma_0_axi_periph_0/XDMA_AXI_BENES_xdma_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_xdma_0_axi_periph_0 || ORIG_REF_NAME==XDMA_AXI_BENES_xdma_0_axi_periph_0} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_2/XDMA_AXI_BENES_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_ila_0_2 || ORIG_REF_NAME==XDMA_AXI_BENES_ila_0_2} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_auto_ds_0/XDMA_AXI_BENES_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_auto_ds_0 || ORIG_REF_NAME==XDMA_AXI_BENES_auto_ds_0} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_auto_pc_0/XDMA_AXI_BENES_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_auto_pc_0 || ORIG_REF_NAME==XDMA_AXI_BENES_auto_pc_0} -quiet] -quiet

# IP: bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/XDMA_AXI_BENES_ila_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_AXI_BENES_ila_0_3 || ORIG_REF_NAME==XDMA_AXI_BENES_ila_0_3} -quiet] -quiet

# XDC: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.gen/sources_1/bd/XDMA_AXI_BENES/XDMA_AXI_BENES_ooc.xdc
