# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.srcs/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/XDMA_AXI_BENES_ila_0_3.xci
# IP: The module: 'XDMA_AXI_BENES_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.gen/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_AXI_BENES_ila_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.gen/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_AXI_BENES_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.gen/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/XDMA_AXI_BENES_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_AXI_BENES_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.srcs/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/XDMA_AXI_BENES_ila_0_3.xci
# IP: The module: 'XDMA_AXI_BENES_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.gen/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_AXI_BENES_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.gen/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_AXI_BENES_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hs/Desktop/Real_prj/XDMA_Block_diagram_PRJ/XDMA_Block_diagram_PRJ.gen/sources_1/bd/XDMA_AXI_BENES/ip/XDMA_AXI_BENES_ila_0_3/XDMA_AXI_BENES_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_AXI_BENES_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
